### ISSUE TITLE
No language for MIME type application/x-newspeak-som-ns found.

### ISSUE THREAD

**Issue by spilot** [spilot/SOMns#2]
```
spilot@T450 ~/U/b/s/SOMns (fredreichbier-super|MERGING)> ./som core-lib/Benchmarks/All.ns 
/home/spilot/.local/graal-core/
Exception in thread "main" java.lang.IllegalStateException: No language for MIME type application/x-newspeak-som-ns found. Supported types: []
	at com.oracle.truffle.api.vm.PolyglotEngine.findLanguage(PolyglotEngine.java:906)
	at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:650)
	at som.VM.startExecution(VM.java:471)
	at som.VM.main(VM.java:404)
```

Seems to occur when I have not done anything for several days. The issue is not exclusively triggered by pulling new commits.

SOMns _usually_ starts to work again after one or _several_ `ant clean` ;  `ant` runs.

**Comment by spilot** [comment]
This seems to be triggered by Eclipse building the project.
