### ISSUE TITLE
java.lang.NoSuchMethodError when trying to execute som

### ISSUE THREAD

**Issue by spilot** [spilot/SOMns#3]
```
spilot@T450 ~/U/b/s/SOMns (master)> env JVMCI_VERSION_CHECK=ignore ./som core-lib/Benchmarks/All.ns 
/home/spilot/.local/graal-core/
Exception in thread "main" java.lang.NoSuchMethodError: com.oracle.truffle.api.impl.TVMCI.getCompilerOptionValues(Lcom/oracle/truffle/api/nodes/RootNode;)Lorg/graalvm/options/OptionValues;
	at org.graalvm.compiler.truffle.GraalTVMCI.getCompilerOptionValues(GraalTVMCI.java:67)
	at org.graalvm.compiler.truffle.PolyglotCompilerOptions.getPolyglotValues(PolyglotCompilerOptions.java:118)
	at org.graalvm.compiler.truffle.OptimizedCallTarget.createCompilationProfile(OptimizedCallTarget.java:289)
	at org.graalvm.compiler.truffle.OptimizedCallTarget.initialize(OptimizedCallTarget.java:280)
	at org.graalvm.compiler.truffle.OptimizedCallTarget.getCompilationProfile(OptimizedCallTarget.java:171)
	at org.graalvm.compiler.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:219)
	at org.graalvm.compiler.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:212)
	at org.graalvm.compiler.truffle.OptimizedCallTarget.call(OptimizedCallTarget.java:190)
	at com.oracle.truffle.api.vm.PolyglotEngine$1.compute(PolyglotEngine.java:659)
	at com.oracle.truffle.api.vm.ComputeInExecutor.run(ComputeInExecutor.java:96)
	at com.oracle.truffle.api.vm.ComputeInExecutor.perform(ComputeInExecutor.java:83)
	at com.oracle.truffle.api.vm.PolyglotEngine.evalImpl(PolyglotEngine.java:662)
	at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:646)
	at som.VM.startExecution(VM.java:462)
	at som.VM.main(VM.java:403)

```

**Comment by spilot** [comment]
Does not happen when som is invoked with the `-G` option. Maybe Graal is outdated.

**Comment by spilot** [comment]
Problem does not occur anymore after re-building Graal, Truffle and SOMns
